// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrBZ4dYIqHcn-3OOuK8F6jihN_fQGivKU',
    appId: '1:83646799493:web:68403abd3b1e8d940393ec',
    messagingSenderId: '83646799493',
    projectId: 'todoc13sun-5bd46',
    authDomain: 'todoc13sun-5bd46.firebaseapp.com',
    storageBucket: 'todoc13sun-5bd46.firebasestorage.app',
    measurementId: 'G-WWWNB1YXPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQE8X5fcGfyrHfY_IY-yPMFH6wq_lAENk',
    appId: '1:83646799493:android:c6690fd0e2bf7f340393ec',
    messagingSenderId: '83646799493',
    projectId: 'todoc13sun-5bd46',
    storageBucket: 'todoc13sun-5bd46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkbGXBAQRF78hLfb5fP1VD6YPpNzuxjfM',
    appId: '1:83646799493:ios:c2f52d3798b431070393ec',
    messagingSenderId: '83646799493',
    projectId: 'todoc13sun-5bd46',
    storageBucket: 'todoc13sun-5bd46.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkbGXBAQRF78hLfb5fP1VD6YPpNzuxjfM',
    appId: '1:83646799493:ios:c2f52d3798b431070393ec',
    messagingSenderId: '83646799493',
    projectId: 'todoc13sun-5bd46',
    storageBucket: 'todoc13sun-5bd46.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrBZ4dYIqHcn-3OOuK8F6jihN_fQGivKU',
    appId: '1:83646799493:web:41111ed423f6fdcd0393ec',
    messagingSenderId: '83646799493',
    projectId: 'todoc13sun-5bd46',
    authDomain: 'todoc13sun-5bd46.firebaseapp.com',
    storageBucket: 'todoc13sun-5bd46.firebasestorage.app',
    measurementId: 'G-BWNQ68DQT0',
  );

}